## Final Model for Error Analysis

### Which model you are analyzing?
- Currently I am analyzing XGBoost mode which predicts that customer will default their payment next month or NOT.

### Why this model was selected?
- Because this model is giving best roc_auc and recall values among others (Gradient Boosting and Random Forest) that is why i am using this model.

### Which threshold is being used?
- Threshold is 0.5 which is default because we did not changed it yet.

In [35]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split

xgb_final_model = joblib.load("xgb_balanced.joblib")

df = df = pd.read_csv("cleaned_data.csv", index_col="id")

x = df.drop(columns=["default_payment_next_month"])
y = df["default_payment_next_month"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [36]:
y_prob = xgb_final_model.predict_proba(x_test)[:, 1]
y_pred = xgb_final_model.predict(x_test)

result = x_test.copy()
result["y_true"] = y_test.values
result["y_pred"] = y_pred
result["y_prob"] = y_prob

result.head()

       limit_bal  sex  education  marriage  ...  pay_amt6  y_true  y_pred    y_prob
id                                          ...
8688       50000    2          3         1  ...      4000       0       0  0.353335
24202     240000    1          2         1  ...      7000       0       0  0.221826
27783      90000    2          1         2  ...      1000       0       0  0.371585
14948      50000    2          2         2  ...      1142       0       0  0.439358
1487      230000    1          1         2  ...      5000       0       0  0.060581

[5 rows x 26 columns]

In [37]:
(result["y_pred"] == (result["y_prob"] >= 0.5).astype("int64")).value_counts()

True    5993
Name: count, dtype: int64

## Categorize Errors

In [42]:
result["error_type"] = "correct"

result.loc[(result["y_true"] == 1) & (result["y_pred"] == 0), "error_type"] = "false_negative"

result.loc[(result["y_true"] == 0) & (result["y_pred"] == 1), "error_type"] = "false_positive"

result["error_type"].value_counts()

error_type
correct           4535
false_positive     968
false_negative     490
Name: count, dtype: int64

### Which error dominates?
- false positive is the error that dominates.

### Why this is expected for this problem?
- Because we are keeping recall high which in return is flagging non-defaulters as defaulters. So that is the reason their are more false positive.

### Which error is more costly?
- Of course false negative is more costly because it means that defaulters are being flagged as non-defaulters which is direct loss to business and thus more costly.

## Inspecting Errors

In [48]:
result[result.error_type == "false_negative"].head(3)

       limit_bal  sex  education  ...  y_pred    y_prob      error_type
id                                ...
1072      150000    2          2  ...       0  0.257188  false_negative
29081     120000    2          2  ...       0  0.477090  false_negative
13754     180000    1          1  ...       0  0.263349  false_negative

[3 rows x 27 columns]

In [51]:
result[result.error_type == "false_positive"].head(3)

       limit_bal  sex  education  ...  y_pred    y_prob      error_type
id                                ...
23515     120000    2          2  ...       1  0.881077  false_positive
14933      20000    1          2  ...       1  0.883030  false_positive
17588      70000    2          2  ...       1  0.801147  false_positive

[3 rows x 27 columns]